### ISSUE TITLE
User kick when use IA emoji in custom channel command

### ISSUE THREAD

**Issue by Barlaf** [Aust1n46/VentureChat#128]
Hello !
When an user use an ItemAdder custom emoji in private channel, the user was kick with message "Illegal characters in chat" only when using the commande. if channel was previously selected and write the emoji, it's work !
### Console log
```
[17:04:13 INFO]: Barlaf issued server command: /stc :tag_guide:
[17:04:13 INFO]: Barlaf lost connection: Illegal characters in chat
```
### config.yml
```yml
channels: 
  Global:
    color: white
    chatcolor: white
    mutable: false
    filter: true
    autojoin: true
    default: true
    distance: 0
    cooldown: 0
    bungeecord: true
    alias: global
    permissions: None
    speak_permissions: None
    channel_prefix: ''
    format: '{vault_prefix}{player_displayname} {vault_suffix}&7►'
  Staff:
    color: light_purple
    chatcolor: light_purple
    mutable: false
    filter: false
    autojoin: true
    default: false
    distance: 0
    cooldown: 0
    bungeecord: true
    alias: stc
    permissions: staffchannel
    speak_permissions: None
    channel_prefix: '&f[&aStaff&f]'
    format: '&7[&6&lSTAFF&r&7] {vault_prefix}{player_displayname} &7►'
```
