### ISSUE TITLE
Gui Menu add lore

### ISSUE THREAD

**Issue by Aathoss** [Aust1n46/VentureChat#13]
Hello,

It would be very interesting to be able to add a description to the items in the GUI interface
Example
```
venturegui:
  mute:
    icon: 'REDSTONE_BLOCK'
    durability: 0
    text: '&cMute {player_name} &410m'
    lore: 
      - '&4Order reminder'
      - '&cMute <player_name> &4<time>'
      - ''
      - '&6Player penalized %player_mutes_count% times'
    permission: 'mute'
    command: '/mute {player_name} 10m'
    slot: 9
```

Thank you in advance for your return
