### ISSUE TITLE
Channel support for towny: ally channel

### ISSUE THREAD

**Issue by Fer-Jg** [Aust1n46/VentureChat#54]
Literally just what the title says, add support for the ally channel for towny compatibility, there is already town and nation support but users also use/need ally chat support, which is (afaik) currently not supported by venturechat and I can not think of a workaround for it.

I tried this and didn't work (+ config instructions is not clear if this is possible):
```yaml
  Alliance:
    color: dark_green
    chatcolor: dark_green
    mutable: true
    filter: true
    autojoin: true
    default: false
    distance: 0
    cooldown: 0
    bungeecord: false
    alias: allies
    permissions: None
    speak_permissions: None
    channel_prefix: '[AL]'
    format: '{venturechat_channel_prefix} &8[{townyadvanced_nation_tag_override} &8| &6{townyadvanced_town_tag_override}&8] &r{luckperms_prefix} &r{essentials_nickname}&7 »&#D6D6D6'
    ```
