### ISSUE TITLE
Messages are not sperarated from the format prefix, when message is sent via alias

### ISSUE THREAD

**Issue by MarvinKlar** [Aust1n46/VentureChat#88]
Hello,

I do use VentureChat on my server, but when I use a channel via the configured alias (`/s` in this case) there is no space between the message and the format prefix (The first message is sent normal via chat, and the second one via `/s Test2`):
https://prnt.sc/7JEEBv29-b6l

Here is the configuration of the channel:
```
  Sprechen:
    color: green
    chatcolor: green
    mutable: true
    filter: false
    autojoin: true
    default: false
    distance: 15
    cooldown: 0
    bungeecord: false
    alias: s
    permissions: None
    speak_permissions: None
    format: '&8[Sprechen] &7{faction_playertitle} {player_displayname}:&a'
```

PaperMC Version: 1.17.1
VentureChat version: 3.6.0
